# Experiment-specific hyperparameters

# environment/computational parameters
seed: 32678456782
device: cpu
num_workers: 4

# dataset parameters
data_root: '/mnt/c/Users/rache/Dropbox/Doctoral_projects/Projects/Piospheres/Final Images/dataset_COCO'
anno_root: '/mnt/c/Users/rache/Dropbox/Doctoral_projects/Projects/Piospheres/Final Images/dataset_COCO/labels'
num_classes: 2

# training hyperparameters
image_size: [256, 256]
num_epochs: 200
batch_size: 32
learning_rate: 0.00001
weight_decay: 0.1